modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/dima-dencep/rrls/issues"
license = "OSL-3.0"

[[mods]]
displayTest = "IGNORE_SERVER_VERSION"
modId = "rrls"
version = "${version}"
displayURL = "https://curseforge.com/minecraft/mc-mods/rrls"
displayName = "Remove Reloading Screen"
updateJSONURL = "https://api.modrinth.com/updates/rrls/forge_updates.json"
authors = "dima_dencep"
description = "Makes resource packs load in the background, allowing you to do other things while waiting!"
logoFile = "icon.png"

[[mixins]]
config = "rrls.mixins.json"
[[mixins]]
config = "rrls-common.mixins.json"

[[dependencies.rrls]]
modId = "neoforge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.rrls]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rrls]]
modId = "cloth_config"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"